# Generated by Django 6.1.1 on 2026-10-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('business_type', models.CharField(blank=True, choices=[('', 'Any business type'), ('retail', 'Retail'), ('food_service', 'Food service'), ('professional_services', 'Professional services'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('minimum_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('why_required', models.TextField()),
                ('documents_needed', models.TextField()),
                ('application_steps', models.TextField()),
                ('official_source_url', models.URLField(blank=True)),
                ('official_portal_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequirementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('document_uploaded', 'Document uploaded')], default='applied', max_length=24)),
                ('applied_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_applications', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='compliance.compliancerequirement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'requirement'), name='unique_user_requirement_application')],
            },
        ),
    ]
