# Generated by Django 6.1.1 on 2026-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerequirement',
            name='official_portal_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='official_source_url',
            field=models.URLField(),
        ),
    ]
