# Generated by Django 6.1.1 on 2026-10-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('food_service', 'Food service'), ('professional_services', 'Professional services'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=40)),
                ('business_activity', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
